import torch
print('Torch ok')
import torchaudio
print('Torchaudio ok')
import torchvision
print('Torchvision ok')
import numpy
print('Numpy ok')
import librosa
print('Librosa ok')
import matplotlib.pyplot as plt
print('Matplotlib ok')
import pytorch_lightning
print('Pytorch_lightning ok')
import torch_stoi
print('Torch_stoi ok')
import torch_mir_eval
print('Torch_mir_eval ok')
import pesq
print('PESQ ok')
import mir_eval
print('MIR_EVAL ok')
import scipy
print('Scipy ok')
